#!/usr/bin/env bash
# Probe CPU / RAM / GPU and write host.auto.env for the other Linux scripts.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${HOST_ENV_FILE:-$ROOT/host.auto.env}"

mem_kb() { awk '/MemTotal:/ {print $2}' /proc/meminfo; }
mem_gb() { awk -v k="$(mem_kb)" 'BEGIN { printf "%d", int(k/1024/1024) }'; }
avail_gb() { awk '/MemAvailable:/ { printf "%d", int($2/1024/1024) }' /proc/meminfo; }

cpu_flags() {
  # First flags: line is enough; /proc/cpuinfo repeats per core.
  awk '/^flags[[:space:]]*:/ {print; exit}' /proc/cpuinfo
}

has_flag() {
  grep -qw "$1" <<<"$FLAGS"
}

FLAGS="$(cpu_flags)"
MEM_GB="$(mem_gb)"
AVAIL_GB="$(avail_gb)"
THREADS="$(nproc)"
HAS_AVX2=0
HAS_AVX512=0
HAS_AMX=0
HAS_NVIDIA=0
HAS_DRM=0
CPU_VARIANT=avx
PROFILE=sandbox-4b
CHAT_HF_REPO="unsloth/Qwen3-4B-GGUF"
CHAT_HF_FILE="Qwen3-4B-Q4_K_M.gguf"
CTX=4096
LLM_MEM_LIMIT=8g

has_flag avx2 && HAS_AVX2=1
has_flag avx512f && HAS_AVX512=1
has_flag amx_int8 && HAS_AMX=1
if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1; then
  HAS_NVIDIA=1
elif [[ -e /dev/nvidia0 ]]; then
  HAS_NVIDIA=1
fi
[[ -e /dev/dri/renderD128 ]] && HAS_DRM=1

GPU_NAME=none
GPU_VRAM_MB=0
if [[ "$HAS_NVIDIA" -eq 1 ]]; then
  GPU_NAME="$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 | sed 's/[[:space:]]*$//' || echo nvidia)"
  GPU_VRAM_MB="$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -d ' ' || echo 0)"
fi

if [[ "$HAS_AVX2" -eq 1 || "$HAS_AVX512" -eq 1 ]]; then
  CPU_VARIANT=native
fi

# Pick the strongest GGUF that still leaves RAM for OS + llama-server + optional embed.
# Weights are mmap'd; keep ~3–4 GB headroom above the file size.
if [[ "$HAS_NVIDIA" -eq 1 && "$MEM_GB" -ge 28 ]]; then
  # 1660 Ti 6GB + 32GB RAM: 35B MoE (3B active) in RAM, CUDA offload fills VRAM.
  PROFILE=gpu-1660ti-32g
  CPU_VARIANT=cuda
  CHAT_HF_REPO="unsloth/Qwen3.5-35B-A3B-GGUF"
  CHAT_HF_FILE="Qwen3.5-35B-A3B-Q3_K_M.gguf"
  CTX=8192
  LLM_MEM_LIMIT=20g
elif [[ "$HAS_NVIDIA" -eq 1 ]]; then
  PROFILE=gpu
  CHAT_HF_REPO="unsloth/Qwen3.5-9B-GGUF"
  CHAT_HF_FILE="Qwen3.5-9B-Q5_K_M.gguf"
  CTX=8192
  LLM_MEM_LIMIT=12g
elif [[ "$MEM_GB" -ge 14 && "$HAS_AVX2" -eq 1 ]]; then
  # 16 GB class Linux box (this Cloud Agent): Qwen3.5-9B Q5 ~6.6 GB.
  PROFILE=host-9b-q5
  CHAT_HF_REPO="unsloth/Qwen3.5-9B-GGUF"
  CHAT_HF_FILE="Qwen3.5-9B-Q5_K_M.gguf"
  CTX=4096
  LLM_MEM_LIMIT=10g
elif [[ "$MEM_GB" -ge 10 && "$HAS_AVX2" -eq 1 ]]; then
  PROFILE=host-9b-q4
  CHAT_HF_REPO="unsloth/Qwen3.5-9B-GGUF"
  CHAT_HF_FILE="Qwen3.5-9B-Q4_K_M.gguf"
  CTX=4096
  LLM_MEM_LIMIT=9g
else
  # i7-2600 / 8–12 GB Docker: original sandbox 4B Q4.
  PROFILE=sandbox-4b
  CPU_VARIANT=avx
  CHAT_HF_REPO="unsloth/Qwen3-4B-GGUF"
  CHAT_HF_FILE="Qwen3-4B-Q4_K_M.gguf"
  CTX=4096
  LLM_MEM_LIMIT=8g
fi

NGL=0
WHISPER_DEVICE=cpu
WHISPER_COMPUTE_TYPE=int8
WHISPER_MODEL=small
if [[ "$HAS_NVIDIA" -eq 1 ]]; then
  NGL=99
  # 6 GB cards: keep whisper on CPU so llama.cpp can fill VRAM.
  if [[ "${GPU_VRAM_MB:-0}" -ge 10000 ]]; then
    WHISPER_DEVICE=cuda
    WHISPER_COMPUTE_TYPE=float16
    WHISPER_MODEL=medium
  else
    WHISPER_DEVICE=cpu
    WHISPER_COMPUTE_TYPE=int8
    WHISPER_MODEL=medium
  fi
elif [[ "$MEM_GB" -ge 14 ]]; then
  # 16 GB host: try medium int8; start-whisper.sh falls back to small if 9B left too little RAM.
  WHISPER_MODEL=medium
fi

cat >"$OUT" <<EOF
# Generated by scripts/detect-hw.sh — do not commit.
LLAMA_CPU_VARIANT=$CPU_VARIANT
HOST_PROFILE=$PROFILE
CHAT_HF_REPO=$CHAT_HF_REPO
CHAT_HF_FILE=$CHAT_HF_FILE
CHAT_GGUF=qwen-chat.gguf
EMBED_HF_REPO=Qwen/Qwen3-Embedding-0.6B-GGUF
EMBED_HF_FILE=Qwen3-Embedding-0.6B-Q8_0.gguf
EMBED_GGUF=qwen-embed.gguf
LLAMA_THREADS=$THREADS
LLAMA_CTX=$CTX
LLAMA_NGL=$NGL
LLM_MEM_LIMIT=$LLM_MEM_LIMIT
WHISPER_DEVICE=$WHISPER_DEVICE
WHISPER_COMPUTE_TYPE=$WHISPER_COMPUTE_TYPE
WHISPER_MODEL=$WHISPER_MODEL
WHISPER_PORT=8000
GPU_NAME="$GPU_NAME"
GPU_VRAM_MB=$GPU_VRAM_MB
EOF

{
  echo "mem_total_gb=$MEM_GB mem_avail_gb=$AVAIL_GB threads=$THREADS"
  echo "avx2=$HAS_AVX2 avx512=$HAS_AVX512 amx=$HAS_AMX nvidia=$HAS_NVIDIA drm=$HAS_DRM"
  echo "gpu_name=$GPU_NAME gpu_vram_mb=$GPU_VRAM_MB"
  echo "cpu_variant=$CPU_VARIANT profile=$PROFILE"
  echo "chat=$CHAT_HF_REPO/$CHAT_HF_FILE ctx=$CTX ngl=$NGL"
  echo "whisper device=$WHISPER_DEVICE compute=$WHISPER_COMPUTE_TYPE model=$WHISPER_MODEL"
  echo "wrote $OUT"
} >&2
