#!/usr/bin/env bash
# Probe CPU / RAM / GPU and write host.auto.env for the other Linux scripts.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${HOST_ENV_FILE:-$ROOT/host.auto.env}"

mem_kb() { awk '/MemTotal:/ {print $2}' /proc/meminfo; }
mem_gb() { awk -v k="$(mem_kb)" 'BEGIN { printf "%d", int(k/1024/1024) }'; }
avail_gb() { awk '/MemAvailable:/ { printf "%d", int($2/1024/1024) }' /proc/meminfo; }

cpu_flags() {
  # First flags: line is enough; /proc/cpuinfo repeats per core.
  awk '/^flags[[:space:]]*:/ {print; exit}' /proc/cpuinfo
}

has_flag() {
  grep -qw "$1" <<<"$FLAGS"
}

FLAGS="$(cpu_flags)"
MEM_GB="$(mem_gb)"
AVAIL_GB="$(avail_gb)"
THREADS="$(nproc)"
HAS_AVX2=0
HAS_AVX512=0
HAS_AMX=0
HAS_NVIDIA=0
CPU_VARIANT=avx
PROFILE=sandbox-4b
CHAT_HF_REPO="unsloth/Qwen3-4B-GGUF"
CHAT_HF_FILE="Qwen3-4B-Q4_K_M.gguf"
CTX=4096
LLM_MEM_LIMIT=8g

has_flag avx2 && HAS_AVX2=1
has_flag avx512f && HAS_AVX512=1
has_flag amx_int8 && HAS_AMX=1
command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1 && HAS_NVIDIA=1

if [[ "$HAS_AVX2" -eq 1 || "$HAS_AVX512" -eq 1 ]]; then
  CPU_VARIANT=native
fi

# Pick the strongest GGUF that still leaves RAM for OS + llama-server + optional embed.
# Weights are mmap'd; keep ~3–4 GB headroom above the file size.
if [[ "$HAS_NVIDIA" -eq 1 ]]; then
  PROFILE=gpu
  CHAT_HF_REPO="unsloth/Qwen3.5-9B-GGUF"
  CHAT_HF_FILE="Qwen3.5-9B-Q5_K_M.gguf"
  CTX=8192
  LLM_MEM_LIMIT=12g
elif [[ "$MEM_GB" -ge 14 && "$HAS_AVX2" -eq 1 ]]; then
  # 16 GB class Linux box (this Cloud Agent): Qwen3.5-9B Q5 ~6.6 GB.
  PROFILE=host-9b-q5
  CHAT_HF_REPO="unsloth/Qwen3.5-9B-GGUF"
  CHAT_HF_FILE="Qwen3.5-9B-Q5_K_M.gguf"
  CTX=4096
  LLM_MEM_LIMIT=10g
elif [[ "$MEM_GB" -ge 10 && "$HAS_AVX2" -eq 1 ]]; then
  PROFILE=host-9b-q4
  CHAT_HF_REPO="unsloth/Qwen3.5-9B-GGUF"
  CHAT_HF_FILE="Qwen3.5-9B-Q4_K_M.gguf"
  CTX=4096
  LLM_MEM_LIMIT=9g
else
  # i7-2600 / 8–12 GB Docker: original sandbox 4B Q4.
  PROFILE=sandbox-4b
  CPU_VARIANT=avx
  CHAT_HF_REPO="unsloth/Qwen3-4B-GGUF"
  CHAT_HF_FILE="Qwen3-4B-Q4_K_M.gguf"
  CTX=4096
  LLM_MEM_LIMIT=8g
fi

NGL=0
if [[ "$HAS_NVIDIA" -eq 1 ]]; then
  NGL=99
fi

cat >"$OUT" <<EOF
# Generated by scripts/detect-hw.sh — do not commit.
LLAMA_CPU_VARIANT=$CPU_VARIANT
HOST_PROFILE=$PROFILE
CHAT_HF_REPO=$CHAT_HF_REPO
CHAT_HF_FILE=$CHAT_HF_FILE
CHAT_GGUF=qwen-chat.gguf
EMBED_HF_REPO=Qwen/Qwen3-Embedding-0.6B-GGUF
EMBED_HF_FILE=Qwen3-Embedding-0.6B-Q8_0.gguf
EMBED_GGUF=qwen-embed.gguf
LLAMA_THREADS=$THREADS
LLAMA_CTX=$CTX
LLAMA_NGL=$NGL
LLM_MEM_LIMIT=$LLM_MEM_LIMIT
EOF

{
  echo "mem_total_gb=$MEM_GB mem_avail_gb=$AVAIL_GB threads=$THREADS"
  echo "avx2=$HAS_AVX2 avx512=$HAS_AVX512 amx=$HAS_AMX nvidia=$HAS_NVIDIA"
  echo "cpu_variant=$CPU_VARIANT profile=$PROFILE"
  echo "chat=$CHAT_HF_REPO/$CHAT_HF_FILE ctx=$CTX ngl=$NGL"
  echo "wrote $OUT"
} >&2
